import pytest
from django.contrib.auth.models import User
from django.urls import reverse
from faker import Faker
from rest_framework import status
from rest_framework.test import APIClient
from rest_framework_simplejwt.tokens import RefreshToken

from apps.tasks.models import Task

fake = Faker("pt_BR")

@pytest.fixture
def api_client():
    """Generates the client tests of Django Rest Framework"""
    return APIClient()

@pytest.fixture
def user_alex(db):
    """Created user Alex in the  test db"""
    return User.objects.create_user(username="alex", password="senha_segura123")


@pytest.fixture
def user_beatriz(db):
    """Created user Beatriz in the test db"""
    return User.objects.create_user(username="beatriz", password="senha_segura456")


@pytest.fixture
def token_alex(user_alex):
    """Token generated JWT for Alex automatic"""
    refresh = RefreshToken.for_user(user_alex)
    return str(refresh.access_token)


@pytest.fixture
def api_client_auth(api_client, token_alex):
    """Return the already authenticated HTTP client with the Alex Token"""
    api_client.credentials(HTTP_AUTHORIZATION=f"Bearer {token_alex}")
    return api_client


@pytest.mark.django_db
def test_create_task_with_faker(api_client_auth, user_alex):
    """Ensure the creation of a task using Faker"""
    url = reverse("task-list")
    
    # Faker generates random data
    payload = {
        "title": fake.catch_phrase(),
        "description": fake.text(max_nb_chars=100),
        "priority": "M",
    }

    response = api_client_auth.post(url, payload, format="json")

    assert response.status_code == status.HTTP_201_CREATED
    assert response.data["title"] == payload["title"]
    assert Task.objects.latest("id").user == user_alex


@pytest.mark.django_db
def test_create_task_unauthenticated(api_client):
    """Ensure that requests without token fail"""
    url = reverse("task-list")
    payload = {"title": fake.word(), "description": fake.text()}
    
    response = api_client.post(url, payload, format="json")

    assert response.status_code == status.HTTP_401_UNAUTHORIZED


@pytest.mark.django_db
def test_get_queryset_privacy_with_pytest(api_client_auth, user_alex, user_beatriz):
    """Test if Alex can't see data generated by Beatriz"""
    url = reverse("task-list")

    #  Created 1 task for Alex using the Faker
    Task.objects.create(
        title=fake.catch_phrase(),
        description=fake.text(max_nb_chars=50),
        priority="L",
        user=user_alex,
    )

    #  Created 3 random tasks for Beatriz
    for _ in range(3):
        Task.objects.create(
            title=fake.catch_phrase(),
            description=fake.text(max_nb_chars=50),
            priority="H",
            user=user_beatriz,
        )
        
    response = api_client_auth.get(url)
    assert response.status_code == status.HTTP_200_OK
    results = response.data.get("results", response.data)
    # Alex should only be able to see 1 task in the return of his listing
    assert len(results) == 1
        
@pytest.mark.django_db
def test_create_task_high_priority_requires_long_description(api_client_auth):
    """Ensures that the High priority ('H') is more  than 20 characters"""
    url = reverse("task-list")
    
    payload = {
        "title": fake.catch_phrase(),
        "description": "Curta demais",
        "priority": "H",
    }

    response = api_client_auth.post(url, payload, format="json")

    # Must fail with 400 Bad Request because of Serializer validation
    assert response.status_code == status.HTTP_400_BAD_REQUEST
    assert "description" in response.data

    
@pytest.mark.django_db
def test_create_task_high_priority_with_valid_description(api_client_auth):
    """ Ensures that the High priority ('H') is more  than 20 characters"""
    url = reverse("task-list")
    
    payload = {
        "title": fake.catch_phrase(),
        "description": "Esta descrição é bem longa e possui mais de vinte caracteres.",
        "priority": "H",
    }

    response = api_client_auth.post(url, payload, format="json")

    assert response.status_code == status.HTTP_201_CREATED

    
@pytest.mark.django_db
def test_task_completed_field_defaults_to_false(api_client_auth):
    """Ensures that the 'completed' field is False, when don't send"""
    url = reverse("task-list")
    
    payload = {
        "title": fake.catch_phrase(),
        "description": fake.text(max_nb_chars=100),
        "priority": "L",
    }

    response = api_client_auth.post(url, payload, format="json")

    assert response.status_code == status.HTTP_201_CREATED
    # Verify if value of model/serializer is applied with False
    assert response.data["completed"] is False


@pytest.mark.django_db
def test_update_task_fields(api_client_auth, user_alex):
    """Ensures that (PUT/PATCH) it's OK"""
    # Created innitial task
    task = Task.objects.create(
        title="Título Antigo",
        description="Descrição antiga com mais de vinte caracteres aqui.",
        priority="L",
        user=user_alex,
    )
    
    url = reverse("task-detail", args=[task.id])
    payload = {"title": "Título Novo", "completed": True}

    # PATCH 
    response = api_client_auth.patch(url, payload, format="json")

    assert response.status_code == status.HTTP_200_OK
    assert response.data["title"] == "Título Novo"
    assert response.data["completed"] is True

@pytest.mark.django_db
def test_alex_cannot_modify_or_delete_beatriz_task(api_client_auth, user_beatriz):
    """Security test"""
    task_beatriz = Task.objects.create(
        title="Secreta da Beatriz", 
        description="Descrição longa da tarefa da Beatriz aqui.", 
        priority="M", 
        user=user_beatriz
    )
    url = reverse("task-detail", args=[task_beatriz.id])
    
    # Alex PATCH in Beatriz task
    response_patch = api_client_auth.patch(url, {"title": "Invasão"}, format="json")
    assert response_patch.status_code == status.HTTP_404_NOT_FOUND

    # Alex DELETE in Beatriz task
    response_delete = api_client_auth.delete(url)
    assert response_delete.status_code == status.HTTP_404_NOT_FOUND

@pytest.mark.django_db
def test_title_max_length_validation(api_client_auth):
    """Field limit test"""
    url = reverse("task-list")
    payload = {
        "title": "X" * 260,
        "description": fake.text(max_nb_chars=100),
        "priority": "L"
    }
    response = api_client_auth.post(url, payload, format="json")
    assert response.status_code == status.HTTP_400_BAD_REQUEST
    assert "title" in response.data
